version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../..:/app
    environment:
      - FLASK_APP=backend.main
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
