version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
